### ISSUE TITLE
Create a title screen

### ISSUE THREAD

**Issue by alex-mike-mark-again** [alex-mike-mark-again/tower-offense#12]
We need a title screen! It doesn't need to look nice right now, but it does have to have

- The title fo the game
- Some way to start the game (something that transitions to another scene. Let's say the example scene for now.)
- Some way to quit the game (as in, close it. probably a button!)
- Some instructions for the game (placeholder text right now)

**Comment by froghood** [comment]
can we assume that our game accepts mouse input only?

**Comment by alex-mike-mark-again** [comment]
Yeah, mouse only
