### ISSUE TITLE
Create the EntityManager

### ISSUE THREAD

**Issue by alex-mike-mark-again** [alex-mike-mark-again/tower-offense#16]
This is an important piece of kit! The EntityManager needs to know what towers and what enemies are on screen, check their proximity between each other, and make decisions about what enemies are taking damage based on that.

The EntityManager is in both the ShopScene and the WaveScene. The ShopScene will add towers to the manager, and the WaveScene will add enemies to it.

The EntityManager should listen for the `Form.Closed` event discovered in #10 to stop tracking destroyed enemies. It should also listen for a yet undefined event that the enemies can emit called `explode.`

With the EntityManager, we can start implementing damaging towers and damaging the player.

**Comment by froghood** [comment]
i think i have a decent idea for this
